package edu.nyu.cs.javagit.cli.init;

import edu.nyu.cs.javagit.JavaGitException;
import edu.nyu.cs.javagit.cli.ICommandResponse;
import edu.nyu.cs.javagit.cli.IParser;

/**
 * Parser class to parse the output generated by git init and return a <code>GitInitResponse</code> object.
 */
public class GitInitParser implements IParser {

    private GitInitResponse response = new GitInitResponse();

    /**
     * Add the final parsed commit. and returns the response of git init execution.
     */
    public ICommandResponse getResponse() throws JavaGitException {
        return this.response;
    }

    /**
     * Parses a line at a time from the commandline execution output of git init
     */
    public void parseLine(String line) {
        if (line.length() == 0) {
            return;
        }
        // initialized
        if (line.contains("Initialized")) {
            response.setInitialized(true);
        }
        // reinitialized
        else if (line.contains("Reinitialized") || line.contains("Initialized")) {
            response.setReinitialized(true);
        }
    }

    public void processExitCode(int code) {

    }
}
