package edu.nyu.cs.javagit.cli.show;

import edu.nyu.cs.javagit.JavaGitException;
import edu.nyu.cs.javagit.cli.ICommandResponse;
import edu.nyu.cs.javagit.cli.IParser;

/**
 * Parser class to parse the output generated by git show; and return a <code>GitShowResponse</code> object.
 */
public class GitShowParser implements IParser {

    public void parseLine(String line) {
        // TODO Auto-generated method stub

    }

    public void processExitCode(int code) {
        // TODO Auto-generated method stub

    }

    public ICommandResponse getResponse() throws JavaGitException {
        // TODO Auto-generated method stub
        return null;
    }

}
