/**
 *  This file is part of LogiSima (http://www.logisima.com).
 *
 *  JavGit is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  JavGit is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with LogiSima-Common.  If not, see <http://www.gnu.org/licenses/>.
 *  
 *  @author Benoît Simard
 *  @See https://github.com/sim51/javagit
 */
package com.logisima.javagit.cli.init;

import com.logisima.javagit.JavaGitException;
import com.logisima.javagit.cli.Parser;

/**
 * Parser class to parse the output generated by git init and return a <code>GitInitResponse</code> object.
 */
public class GitInitParser extends Parser {

    private GitInitResponse response;

    /**
     * Constructor.
     */
    public GitInitParser() {
        super();
        response = new GitInitResponse();
    }

    /**
     * Parses a line at a time from the commandline execution output of git init
     */
    public void parseLine(String line) {
        if (line.length() == 0) {
            return;
        }
        // initialized
        if (line.contains("Initialized")) {
            response.setInitialized(true);
        }
        // reinitialized
        else if (line.contains("Reinitialized") || line.contains("Initialized")) {
            response.setReinitialized(true);
        }
    }

    @Override
    public GitInitResponse getResponse() throws JavaGitException {
        return response;
    }
}
